# Generated by Django 2.0.3 on 2018-03-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='artigo_img',
            field=models.ImageField(upload_to='img_artigo'),
        ),
    ]
