# Generated by Django 2.0.3 on 2018-04-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0002_auto_20180331_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='artigo_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
