# Generated by Django 2.0.3 on 2018-04-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0004_auto_20180401_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='artigo_img',
            field=models.ImageField(blank=True, upload_to='img_artigos'),
        ),
    ]
