# Generated by Django 2.0 on 2018-04-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0005_auto_20180401_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(default='', max_length=200)),
                ('email_contato', models.CharField(default='', max_length=80)),
                ('end_contato', models.CharField(blank=True, default='', max_length=800)),
                ('cidade_contato', models.CharField(default='', max_length=80)),
                ('estado_contato', models.CharField(default='', max_length=80)),
                ('cep_contato', models.CharField(default='', max_length=10)),
                ('fone_residencial', models.CharField(blank=True, default='', max_length=11)),
                ('fone_comercial', models.CharField(blank=True, default='', max_length=11)),
                ('fone_celular', models.CharField(blank=True, default='', max_length=11)),
                ('txt_mensagem', models.TextField(default='')),
            ],
        ),
    ]
