# Generated by Django 2.0 on 2018-04-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0009_auto_20180405_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='literatura',
            name='classificacao',
            field=models.CharField(choices=[('1', 'Poesia'), ('2', 'Contos'), ('3', 'Microcontos')], default=1, max_length=1),
        ),
    ]
