# Generated by Django 2.0 on 2018-04-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0010_literatura_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='artigo_subtitulo',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='literatura',
            name='classificacao',
            field=models.CharField(choices=[('Poesia', 'Poesia'), ('Contos', 'Contos'), ('Microcontos', 'Microcontos')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='literatura',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
