# Generated by Django 2.0 on 2018-04-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0011_auto_20180406_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literatura',
            name='classificacao',
            field=models.CharField(choices=[('Poesia', 'Poesia'), ('Contos', 'Contos'), ('Microcontos', 'Microcontos')], default='Poesia', max_length=12),
        ),
    ]
