# Generated by Django 2.0 on 2018-04-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0012_auto_20180406_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
    ]
