# Generated by Django 2.0 on 2018-04-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0013_videoteste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoTeste',
        ),
    ]
