# Generated by Django 2.0 on 2018-04-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0017_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('subtitulo', models.CharField(max_length=256)),
                ('comentario', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='data de publicacao')),
            ],
        ),
    ]
