# Generated by Django 2.0 on 2018-04-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0021_quadrinhos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quadrinhos',
            new_name='Quadrinho',
        ),
    ]
