# Generated by Django 2.0 on 2018-04-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0022_auto_20180411_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('subtitulo', models.CharField(max_length=256)),
                ('imagem', models.ImageField(blank=True, upload_to='img_pintura')),
                ('pub_date', models.DateTimeField(verbose_name='data de publicacao')),
            ],
        ),
    ]
