# Generated by Django 2.0 on 2018-04-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0026_videome'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesenhoEK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('subtitulo', models.CharField(max_length=256)),
                ('imagem', models.ImageField(blank=True, upload_to='img_pintura')),
                ('pub_date', models.DateTimeField(verbose_name='data de publicacao')),
            ],
        ),
        migrations.CreateModel(
            name='EstoriaEK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('subtitulo', models.CharField(max_length=256)),
                ('imagem', models.ImageField(blank=True, upload_to='img_pintura')),
                ('pub_date', models.DateTimeField(verbose_name='data de publicacao')),
            ],
        ),
        migrations.CreateModel(
            name='VideoEK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('icon_video', models.ImageField(upload_to='img_video')),
                ('link', models.URLField()),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('desc_video', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='data de publicacao')),
            ],
        ),
    ]
