# Generated by Django 2.0 on 2018-04-13 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0027_desenhoek_estoriaek_videoek'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='dt_hr_envio',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 13, 15, 19, 499258, tzinfo=utc)),
        ),
    ]
